categories:
  - title: ":boom: Breaking Changes"
    when:
      - labels:
          - "breaking"
  - title: ":rocket: Features"
    when:
      - labels:
          - "enhancement"
  - title: ":fire: Removals and Deprecations"
    when:
      - labels:
          - "removal"
  - title: ":beetle: Fixes"
    when:
      - labels:
          - "bug"
  - title: ":racehorse: Performance"
    when:
      - labels:
          - "performance"
  - title: ":rotating_light: Testing"
    when:
      - labels:
          - "testing"
  - title: ":construction_worker: Continuous Integration"
    when:
      - labels:
          - "ci"
  - title: ":books: Documentation"
    when:
      - labels:
          - "documentation"
  - title: ":hammer: Refactoring"
    when:
      - labels:
          - "refactoring"
  - title: ":lipstick: Style"
    when:
      - labels:
          - "style"
  - title: ":package: Dependencies"
    when:
      - labels:
          - "dependencies"
          - "build"
template: |
  ## Changes

  $CHANGES
